// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmbmMKAanyJe6dvmn_VlnNmHYd9V39TQ',
    appId: '1:154729368382:web:03aa2b4870a491b1e83a6f',
    messagingSenderId: '154729368382',
    projectId: 'contact-app-firebase-a1fb4',
    authDomain: 'contact-app-firebase-a1fb4.firebaseapp.com',
    storageBucket: 'contact-app-firebase-a1fb4.firebasestorage.app',
    measurementId: 'G-1G5YRHTT48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFCCSaCybX21adpO5puYBO0gqlrQEnNI',
    appId: '1:154729368382:android:05025d18845973bde83a6f',
    messagingSenderId: '154729368382',
    projectId: 'contact-app-firebase-a1fb4',
    storageBucket: 'contact-app-firebase-a1fb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqwZ2dxBwsZXIS_9frVpllYkhiE_AEhu4',
    appId: '1:154729368382:ios:84428be859ccc3d5e83a6f',
    messagingSenderId: '154729368382',
    projectId: 'contact-app-firebase-a1fb4',
    storageBucket: 'contact-app-firebase-a1fb4.firebasestorage.app',
    iosBundleId: 'uz.sanjar.myNotesEslatmaIlovasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqwZ2dxBwsZXIS_9frVpllYkhiE_AEhu4',
    appId: '1:154729368382:ios:84428be859ccc3d5e83a6f',
    messagingSenderId: '154729368382',
    projectId: 'contact-app-firebase-a1fb4',
    storageBucket: 'contact-app-firebase-a1fb4.firebasestorage.app',
    iosBundleId: 'uz.sanjar.myNotesEslatmaIlovasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqmbmMKAanyJe6dvmn_VlnNmHYd9V39TQ',
    appId: '1:154729368382:web:30c6f7c7697e9088e83a6f',
    messagingSenderId: '154729368382',
    projectId: 'contact-app-firebase-a1fb4',
    authDomain: 'contact-app-firebase-a1fb4.firebaseapp.com',
    storageBucket: 'contact-app-firebase-a1fb4.firebasestorage.app',
    measurementId: 'G-JCWXE0RRFP',
  );
}
